# Generated by Django 2.1.5 on 2019-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20190112_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='country_of_originLabel',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='filmLabel',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pubDate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='genreLabel',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='publicationYear',
            field=models.IntegerField(default=0),
        ),
    ]
