# Generated by Django 2.1.5 on 2019-01-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20190112_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country_of_originLabel',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genreLabel',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='publicationYear',
            new_name='pubYear',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='filmLabel',
            new_name='title',
        ),
    ]
