# Generated by Django 2.1.5 on 2019-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_movie_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pubDate',
            field=models.CharField(max_length=100),
        ),
    ]
